TELEGRAM_BOT_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"
ANALYSIS_INTERVAL_MINUTES = 15
SIGNIFICANCE_THRESHOLD_HIGH = 80
SIGNIFICANCE_THRESHOLD_MID = 70
SIGNIFICANCE_DURATION_MINUTES = 60

SYMBOL = "BTC/USDT"
